version: "2"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "8888:8888"

   db:
     image: mysql:5.7
     ports:
      - "3306:3306"
     volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
     restart: always
     environment:
       MYSQL_DATABASE: words
       MYSQL_ROOT_PASSWORD: root
       MYSQL_USER: words
       MYSQL_PASSWORD: words
